import { FileText, Download, Share2 } from 'lucide-react';

export const ReportsView = () => {
    return (
        <div className="h-full flex flex-col gap-6">
            <div className="flex justify-between items-center">
                <div>
                    <h2 className="text-2xl font-bold tracking-tight">Reports Generation</h2>
                    <p className="text-muted-foreground">Preview and export analysis results.</p>
                </div>
                <div className="flex gap-3">
                    <button className="flex items-center gap-2 px-4 py-2 bg-card border border-border rounded-lg hover:bg-muted font-medium text-sm">
                        <Share2 size={16} />
                        Share Link
                    </button>
                    <button className="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-lg font-medium text-sm hover:bg-primary/90 shadow-lg shadow-primary/25">
                        <Download size={16} />
                        Download PDF
                    </button>
                </div>
            </div>

            <div className="flex-1 flex gap-8 min-h-0">
                {/* Reports List */}
                <div className="w-80 flex flex-col gap-4">
                    <div className="relative">
                        <input className="w-full bg-card border border-border rounded-lg pl-4 pr-10 py-2 text-sm" placeholder="Search reports..." />
                    </div>
                    <div className="flex-1 overflow-auto space-y-2">
                        {[1, 2, 3].map(i => (
                            <div key={i} className={`p-4 rounded-xl border cursor-pointer transition-all ${i === 1 ? 'bg-primary/5 border-primary ring-1 ring-primary' : 'bg-card border-border hover:border-primary/50'}`}>
                                <h4 className="font-semibold text-sm">Analysis_Report_00{i}.pdf</h4>
                                <div className="flex items-center gap-2 mt-2 text-xs text-muted-foreground">
                                    <FileText size={12} />
                                    <span>Dec 11, 2025 • 2.4 MB</span>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* PDF Preview */}
                <div className="flex-1 bg-neutral-200/50 dark:bg-neutral-900/50 rounded-xl border border-border flex flex-col items-center justify-center p-8 overflow-auto">
                    <div className="w-[595px] h-[842px] bg-white text-black shadow-xl rounded-sm p-12 flex flex-col gap-8 scale-90 origin-top">
                        {/* Mock PDF Content */}
                        <div className="flex justify-between items-end border-b-2 border-black pb-4">
                            <div>
                                <h1 className="text-3xl font-bold">Analysis Report</h1>
                                <p className="text-gray-500 mt-1">Sample ID: #8821-X9</p>
                            </div>
                            <div className="text-right text-sm">
                                <p>Date: 12/11/2025</p>
                                <p>Generated by: UniAIMS</p>
                            </div>
                        </div>

                        <div className="grid grid-cols-2 gap-8">
                            <div className="p-4 bg-gray-50 rounded border border-gray-100">
                                <h3 className="uppercase tracking-wider text-xs font-bold text-gray-500 mb-2">Total Count</h3>
                                <p className="text-2xl font-bold">1,245</p>
                            </div>
                            <div className="p-4 bg-gray-50 rounded border border-gray-100">
                                <h3 className="uppercase tracking-wider text-xs font-bold text-gray-500 mb-2">Avg Size</h3>
                                <p className="text-2xl font-bold">4.21 µm</p>
                            </div>
                        </div>

                        <div>
                            <h3 className="font-bold border-b border-gray-200 pb-2 mb-4">Particle Distribution</h3>
                            <div className="h-48 bg-gray-100 rounded flex items-center justify-center text-gray-400">
                                [Chart Placeholder]
                            </div>
                        </div>

                        <div>
                            <h3 className="font-bold border-b border-gray-200 pb-2 mb-4">Conclusion</h3>
                            <p className="text-sm leading-relaxed text-gray-700">
                                The sample shows a high concentration of particles in the 2-4µm range.
                                Fiber contamination is minimal (less than 1%).
                                The distribution suggests a uniform manufacturing process.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};
